### ISSUE TITLE
Where does IR-fuzzer live?  llvm-project repo?

### ISSUE THREAD

**Issue by androm3da** [DataCorrupted/LLVM-fuzzing-trophies#1]
How can I run IR-fuzzer?

Also: any architectures tested other than the ones for which trophies were found?

**Comment by DataCorrupted** [comment]
Hi @androm3da , thanks for the interest.

- We are in the final stages of cleaning up IRFuzzer. We plan to open source it early Dec. I'll send you a notification when we release it. 
- We are testing all `Target` in LLVM, including `Hexagon`. That resulted in a huge amount of data to process. We know there are bugs in other archs we listed here, but we haven't had time to write report about it. We will update this table as soon as we file an issue.
- If you have your own backend and is open-sourced, we are happy to fuzz it for you before Dec.

**Comment by androm3da** [comment]
> We are testing all Target in LLVM, including Hexagon

Excellent!  Curious to hear about the Hexagon results.

**Comment by HazyFish** [comment]
@androm3da Hi! I'm currently working on analyzing Hexagon results. I will cc you for issues I opened in [llvm/llvm-project](https://github.com/llvm/llvm-project/) that's related to Hexagon.

**Comment by DataCorrupted** [comment]
@androm3da Hi, [IRFuzzer](https://github.com/SecurityLab-UCD/IRFuzzer) release 0.1 has been public now. Though we are targeting a forked branch of LLVM. You can port everything in FuzzMutate to your downstream application and start fuzzing!

Upstreaming FuzzMutate is still WIP [1](https://reviews.llvm.org/D139907) [2](https://reviews.llvm.org/D139894).

Please also let me know if there are other mutation algorithms you would like to add, I would happily help.
